@startuml

!theme plain
top to bottom direction
skinparam linetype polyline

class BasicObject {
   initialize:
   !:
   !=:
   ==:
   __id__:
   __send__:
   instance_eval:
   instance_exec:
   method_missing:
   singleton_method_added:
   singleton_method_removed:
   singleton_method_undefined:
}
class Class {
   json_creatable?:
}
class Kernel {
   pretty_inspect:
   pp:
}
class Module {
   constants:
   nesting:
   used_modules:
   initialize:
   <:
   <=:
   <=>:
   ==:
   ===:
   >:
   >=:
   alias_method:
   ancestors:
   attr:
   attr_accessor:
   attr_reader:
   attr_writer:
   autoload:
   autoload?:
   class_variable_defined?:
   class_variable_get:
   class_variable_set:
   class_variables:
   const_defined?:
   const_get:
   const_missing:
   const_set:
   const_source_location:
   constants:
   define_method:
   deprecate_constant:
   freeze:
   include:
   include?:
   included_modules:
   instance_method:
   instance_methods:
   method_defined?:
   module_eval:
   module_exec:
   name:
   prepend:
   private_class_method:
   private_constant:
   private_instance_methods:
   private_method_defined?:
   protected_instance_methods:
   protected_method_defined?:
   public_class_method:
   public_constant:
   public_instance_method:
   public_instance_methods:
   public_method_defined?:
   remove_class_variable:
   remove_method:
   singleton_class?:
   to_s:
   undef_method:
   append_features:
   extend_object:
   extended:
   included:
   method_added:
   method_removed:
   method_undefined:
   module_function:
   prepend_features:
   prepended:
   private:
   protected:
   public:
   refine:
   remove_const:
   ruby2_keywords:
   using:
}
class Object
class Student {
   id:
   surname:
   first_name:
   patronymic:
   phone:
   telegram:
   mail:
   git:
   initials:
   contact:
   initialize:
   student_short:
   set_contacts:
   validate_fields:
   info:
   communication:
   names:
   initials_get:
   to_s:
   from_string:
   validate_contact:
   valid_phone?:
   valid_telegram?:
   valid_mail?:
   valid_git?:
   read_from_txt:
   write_to_txt:
}
class Student_Filtered {
   data_getter:
   initialize:
   get_k_n_student_list:
   get_student_count:
   search:
   apply_filters:
}
class Student_List {
   students:
   initialize:
   add_student:
   get_student:
   update_student:
   delete_student:
   student_count:
   get_k_n_student:
   get_student_count:
   filter:
}
class Student_List_Base {
   load_data:
   save_data:
   sort_by_surname_initials:
   generate_id:
}
class Student_List_JSON {
   file_path:
   data:
   load_data:
   save_data:
}
class Student_List_TXT {
   file_path:
   file_extension:
   students:
   initialize:
   load_data:
   save_data:
}
class Student_List_YAML {
   data:
   load_data:
   save_data:
}
class Student_Search {
   student_getter:
   filters:
   initialize:
   with_surname:
   with_initials:
   with_mail:
   with_phone:
   with_telegram:
   with_git:
   with_mail_present:
   with_phone_present:
   with_telegram_present:
   with_git_present:
   with_mail_missing:
   with_phone_missing:
   with_telegram_missing:
   with_git_missing:
   reset_filters:
   results:
   count:
}
class Students_list_DB {
   conn:
   initialize:
   get_student_by_id:
   get_k_n_student_list:
   add_student:
   replace_student_by_id:
   delete_student_by_id:
   number_of_elements:
   generate_new_id:
}

Class              ^-[#000082,plain]-  Module
Module             ^-[#000082,plain]-  Object
Object             ^-[#000082,plain]-  BasicObject
Object             <-[#008200,dashed]-  Kernel
Student            ^-[#000082,plain]-  Object
Student_Filtered   ^-[#000082,plain]-  Object
Student_List       ^-[#000082,plain]-  Object
Student_List_Base  ^-[#000082,plain]-  Student_List
Student_List_JSON  ^-[#000082,plain]-  Student_List_Base
Student_List_TXT   ^-[#000082,plain]-  Student_List_Base
Student_List_YAML  ^-[#000082,plain]-  Student_List_Base
Student_Search     ^-[#000082,plain]-  Object
Students_list_DB   ^-[#000082,plain]-  Object
@enduml

